name: Update Terraform Cloud Workspace Variables
description: Takes a set of decrypted
inputs:
  organization:
    description: Terraform organization
    required: true

  token:
    description: Terraform Cloud token
    required: true

  address:
    description: Terraform Cloud address
    required: false
    default: https://app.terraform.io

  variables:
    required: false
    description: JSON string object of Terraform Cloud variables

  workspace_tag_filter:
    required: false
    description: Update workspace variables in workspaces with a the passed tag

runs:
  using: docker
  image: Dockerfile
