name: Update Terraform Cloud Workspace Variables
description: Takes a set of decrypted
inputs:
  organization:
    description: Terraform organization
    required: true

  token:
    description: Terraform Cloud token
    required: true

  address:
    description: Terraform Cloud address
    required: false
    default: https://app.terraform.io

  secrets_path:
    required: true
    description: Path to the JSON secrets file

  encrypted_secrets_json:
    required: false
    description: JSON string object of key value encrypted secret vars
runs:
  using: docker
  image: Dockerfile